/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as GestorRouteImport } from './routes/gestor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SolucoesRouteImport } from './routes/solucoes'
import { Route as ColaboradorHistoricoRouteImport } from './routes/colaborador.historico'
import { Route as ColaboradorMensagensRouteImport } from './routes/colaborador.mensagens'
import { Route as ColaboradorMeusEpisRouteImport } from './routes/colaborador.meus-epis'
import { Route as ColaboradorObservacaoRouteImport } from './routes/colaborador.observacao'
import { Route as GestorIndexRouteImport } from './routes/gestor.index'
import { Route as GestorCertificadosRouteImport } from './routes/gestor.certificados'
import { Route as GestorColaboradoresRouteImport } from './routes/gestor.colaboradores'
import { Route as GestorEpisRouteImport } from './routes/gestor.epis'
import { Route as GestorMensagensRouteImport } from './routes/gestor.mensagens'
import { Route as GestorObservacoesRouteImport } from './routes/gestor.observacoes'
import { Route as GestorUsuariosRouteImport } from './routes/gestor.usuarios'
import { Route as GestorObservacoesIdRouteImport } from './routes/gestor.observacoes_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const GestorRoute = GestorRouteImport.update({
  id: '/gestor',
  path: '/gestor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesRoute = SolucoesRouteImport.update({
  id: '/solucoes',
  path: '/solucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboradorHistoricoRoute = ColaboradorHistoricoRouteImport.update({
  id: '/colaborador/historico',
  path: '/colaborador/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboradorMensagensRoute = ColaboradorMensagensRouteImport.update({
  id: '/colaborador/mensagens',
  path: '/colaborador/mensagens',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboradorMeusEpisRoute = ColaboradorMeusEpisRouteImport.update({
  id: '/colaborador/meus-epis',
  path: '/colaborador/meus-epis',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboradorObservacaoRoute = ColaboradorObservacaoRouteImport.update({
  id: '/colaborador/observacao',
  path: '/colaborador/observacao',
  getParentRoute: () => rootRouteImport,
} as any)
const GestorIndexRoute = GestorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GestorRoute,
} as any)
const GestorCertificadosRoute = GestorCertificadosRouteImport.update({
  id: '/certificados',
  path: '/certificados',
  getParentRoute: () => GestorRoute,
} as any)
const GestorColaboradoresRoute = GestorColaboradoresRouteImport.update({
  id: '/colaboradores',
  path: '/colaboradores',
  getParentRoute: () => GestorRoute,
} as any)
const GestorEpisRoute = GestorEpisRouteImport.update({
  id: '/epis',
  path: '/epis',
  getParentRoute: () => GestorRoute,
} as any)
const GestorMensagensRoute = GestorMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => GestorRoute,
} as any)
const GestorObservacoesRoute = GestorObservacoesRouteImport.update({
  id: '/observacoes',
  path: '/observacoes',
  getParentRoute: () => GestorRoute,
} as any)
const GestorUsuariosRoute = GestorUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => GestorRoute,
} as any)
const GestorObservacoesIdRoute = GestorObservacoesIdRouteImport.update({
  id: '/observacoes_/$id',
  path: '/observacoes/$id',
  getParentRoute: () => GestorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/gestor': typeof GestorRouteWithChildren
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/sobre': typeof SobreRoute
  '/solucoes': typeof SolucoesRoute
  '/colaborador/historico': typeof ColaboradorHistoricoRoute
  '/colaborador/mensagens': typeof ColaboradorMensagensRoute
  '/colaborador/meus-epis': typeof ColaboradorMeusEpisRoute
  '/colaborador/observacao': typeof ColaboradorObservacaoRoute
  '/gestor/certificados': typeof GestorCertificadosRoute
  '/gestor/colaboradores': typeof GestorColaboradoresRoute
  '/gestor/epis': typeof GestorEpisRoute
  '/gestor/mensagens': typeof GestorMensagensRoute
  '/gestor/observacoes': typeof GestorObservacoesRoute
  '/gestor/usuarios': typeof GestorUsuariosRoute
  '/gestor/': typeof GestorIndexRoute
  '/gestor/observacoes/$id': typeof GestorObservacoesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/sobre': typeof SobreRoute
  '/solucoes': typeof SolucoesRoute
  '/colaborador/historico': typeof ColaboradorHistoricoRoute
  '/colaborador/mensagens': typeof ColaboradorMensagensRoute
  '/colaborador/meus-epis': typeof ColaboradorMeusEpisRoute
  '/colaborador/observacao': typeof ColaboradorObservacaoRoute
  '/gestor/certificados': typeof GestorCertificadosRoute
  '/gestor/colaboradores': typeof GestorColaboradoresRoute
  '/gestor/epis': typeof GestorEpisRoute
  '/gestor/mensagens': typeof GestorMensagensRoute
  '/gestor/observacoes': typeof GestorObservacoesRoute
  '/gestor/usuarios': typeof GestorUsuariosRoute
  '/gestor': typeof GestorIndexRoute
  '/gestor/observacoes/$id': typeof GestorObservacoesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/gestor': typeof GestorRouteWithChildren
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/sobre': typeof SobreRoute
  '/solucoes': typeof SolucoesRoute
  '/colaborador/historico': typeof ColaboradorHistoricoRoute
  '/colaborador/mensagens': typeof ColaboradorMensagensRoute
  '/colaborador/meus-epis': typeof ColaboradorMeusEpisRoute
  '/colaborador/observacao': typeof ColaboradorObservacaoRoute
  '/gestor/certificados': typeof GestorCertificadosRoute
  '/gestor/colaboradores': typeof GestorColaboradoresRoute
  '/gestor/epis': typeof GestorEpisRoute
  '/gestor/mensagens': typeof GestorMensagensRoute
  '/gestor/observacoes': typeof GestorObservacoesRoute
  '/gestor/usuarios': typeof GestorUsuariosRoute
  '/gestor/': typeof GestorIndexRoute
  '/gestor/observacoes_/$id': typeof GestorObservacoesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/esqueci-senha'
    | '/gestor'
    | '/login'
    | '/planos'
    | '/sobre'
    | '/solucoes'
    | '/colaborador/historico'
    | '/colaborador/mensagens'
    | '/colaborador/meus-epis'
    | '/colaborador/observacao'
    | '/gestor/certificados'
    | '/gestor/colaboradores'
    | '/gestor/epis'
    | '/gestor/mensagens'
    | '/gestor/observacoes'
    | '/gestor/usuarios'
    | '/gestor/'
    | '/gestor/observacoes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/esqueci-senha'
    | '/login'
    | '/planos'
    | '/sobre'
    | '/solucoes'
    | '/colaborador/historico'
    | '/colaborador/mensagens'
    | '/colaborador/meus-epis'
    | '/colaborador/observacao'
    | '/gestor/certificados'
    | '/gestor/colaboradores'
    | '/gestor/epis'
    | '/gestor/mensagens'
    | '/gestor/observacoes'
    | '/gestor/usuarios'
    | '/gestor'
    | '/gestor/observacoes/$id'
  id:
    | '__root__'
    | '/'
    | '/esqueci-senha'
    | '/gestor'
    | '/login'
    | '/planos'
    | '/sobre'
    | '/solucoes'
    | '/colaborador/historico'
    | '/colaborador/mensagens'
    | '/colaborador/meus-epis'
    | '/colaborador/observacao'
    | '/gestor/certificados'
    | '/gestor/colaboradores'
    | '/gestor/epis'
    | '/gestor/mensagens'
    | '/gestor/observacoes'
    | '/gestor/usuarios'
    | '/gestor/'
    | '/gestor/observacoes_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  GestorRoute: typeof GestorRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlanosRoute: typeof PlanosRoute
  SobreRoute: typeof SobreRoute
  SolucoesRoute: typeof SolucoesRoute
  ColaboradorHistoricoRoute: typeof ColaboradorHistoricoRoute
  ColaboradorMensagensRoute: typeof ColaboradorMensagensRoute
  ColaboradorMeusEpisRoute: typeof ColaboradorMeusEpisRoute
  ColaboradorObservacaoRoute: typeof ColaboradorObservacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestor': {
      id: '/gestor'
      path: '/gestor'
      fullPath: '/gestor'
      preLoaderRoute: typeof GestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes': {
      id: '/solucoes'
      path: '/solucoes'
      fullPath: '/solucoes'
      preLoaderRoute: typeof SolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaborador/historico': {
      id: '/colaborador/historico'
      path: '/colaborador/historico'
      fullPath: '/colaborador/historico'
      preLoaderRoute: typeof ColaboradorHistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaborador/mensagens': {
      id: '/colaborador/mensagens'
      path: '/colaborador/mensagens'
      fullPath: '/colaborador/mensagens'
      preLoaderRoute: typeof ColaboradorMensagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaborador/meus-epis': {
      id: '/colaborador/meus-epis'
      path: '/colaborador/meus-epis'
      fullPath: '/colaborador/meus-epis'
      preLoaderRoute: typeof ColaboradorMeusEpisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaborador/observacao': {
      id: '/colaborador/observacao'
      path: '/colaborador/observacao'
      fullPath: '/colaborador/observacao'
      preLoaderRoute: typeof ColaboradorObservacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestor/': {
      id: '/gestor/'
      path: '/'
      fullPath: '/gestor/'
      preLoaderRoute: typeof GestorIndexRouteImport
      parentRoute: typeof GestorRoute
    }
    '/gestor/certificados': {
      id: '/gestor/certificados'
      path: '/certificados'
      fullPath: '/gestor/certificados'
      preLoaderRoute: typeof GestorCertificadosRouteImport
      parentRoute: typeof GestorRoute
    }
    '/gestor/colaboradores': {
      id: '/gestor/colaboradores'
      path: '/colaboradores'
      fullPath: '/gestor/colaboradores'
      preLoaderRoute: typeof GestorColaboradoresRouteImport
      parentRoute: typeof GestorRoute
    }
    '/gestor/epis': {
      id: '/gestor/epis'
      path: '/epis'
      fullPath: '/gestor/epis'
      preLoaderRoute: typeof GestorEpisRouteImport
      parentRoute: typeof GestorRoute
    }
    '/gestor/mensagens': {
      id: '/gestor/mensagens'
      path: '/mensagens'
      fullPath: '/gestor/mensagens'
      preLoaderRoute: typeof GestorMensagensRouteImport
      parentRoute: typeof GestorRoute
    }
    '/gestor/observacoes': {
      id: '/gestor/observacoes'
      path: '/observacoes'
      fullPath: '/gestor/observacoes'
      preLoaderRoute: typeof GestorObservacoesRouteImport
      parentRoute: typeof GestorRoute
    }
    '/gestor/usuarios': {
      id: '/gestor/usuarios'
      path: '/usuarios'
      fullPath: '/gestor/usuarios'
      preLoaderRoute: typeof GestorUsuariosRouteImport
      parentRoute: typeof GestorRoute
    }
    '/gestor/observacoes_/$id': {
      id: '/gestor/observacoes_/$id'
      path: '/observacoes/$id'
      fullPath: '/gestor/observacoes/$id'
      preLoaderRoute: typeof GestorObservacoesIdRouteImport
      parentRoute: typeof GestorRoute
    }
  }
}

interface GestorRouteChildren {
  GestorCertificadosRoute: typeof GestorCertificadosRoute
  GestorColaboradoresRoute: typeof GestorColaboradoresRoute
  GestorEpisRoute: typeof GestorEpisRoute
  GestorMensagensRoute: typeof GestorMensagensRoute
  GestorObservacoesRoute: typeof GestorObservacoesRoute
  GestorUsuariosRoute: typeof GestorUsuariosRoute
  GestorIndexRoute: typeof GestorIndexRoute
  GestorObservacoesIdRoute: typeof GestorObservacoesIdRoute
}

const GestorRouteChildren: GestorRouteChildren = {
  GestorCertificadosRoute: GestorCertificadosRoute,
  GestorColaboradoresRoute: GestorColaboradoresRoute,
  GestorEpisRoute: GestorEpisRoute,
  GestorMensagensRoute: GestorMensagensRoute,
  GestorObservacoesRoute: GestorObservacoesRoute,
  GestorUsuariosRoute: GestorUsuariosRoute,
  GestorIndexRoute: GestorIndexRoute,
  GestorObservacoesIdRoute: GestorObservacoesIdRoute,
}

const GestorRouteWithChildren =
  GestorRoute._addFileChildren(GestorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  GestorRoute: GestorRouteWithChildren,
  LoginRoute: LoginRoute,
  PlanosRoute: PlanosRoute,
  SobreRoute: SobreRoute,
  SolucoesRoute: SolucoesRoute,
  ColaboradorHistoricoRoute: ColaboradorHistoricoRoute,
  ColaboradorMensagensRoute: ColaboradorMensagensRoute,
  ColaboradorMeusEpisRoute: ColaboradorMeusEpisRoute,
  ColaboradorObservacaoRoute: ColaboradorObservacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
